@startuml readelf_buffer

+struct ReadElf {
    .. <<methods>> ..
    +from_slice(buffer: &[u8]): Option<ReadElf>
    +from_vec(buffer: Vec<u8>): Option<ReadElf>
    +open<P: AsRef<Path>>(path: P): Option<ReadElf>
}

+interface BinParser {
    +get_u8(offset: u64, Endian: e): Option<u8>
    +get_u16(offset: u64, Endian: e): Option<u16>
    +get_u32(offset: u64, Endian: e): Option<u32>
    +get_u64(offset: u64, Endian: e): Option<u64>
    +get_usize(offset: u64, Endian: e, Class: c): Option<u64>
}

~struct Slice {
    ~new(buffer: &[u8]): Slice
    +get_u8(offset: u64, Endian: e): Option<u8>
    +get_u16(offset: u64, Endian: e): Option<u16>
    +get_u32(offset: u64, Endian: e): Option<u32>
    +get_u64(offset: u64, Endian: e): Option<u64>
}

~struct VecBuffer {
    ~new(buffer: Vec<u8>): VecBuffer
    +get_u8(offset: u64, Endian: e): Option<u8>
    +get_u16(offset: u64, Endian: e): Option<u16>
    +get_u32(offset: u64, Endian: e): Option<u32>
    +get_u64(offset: u64, Endian: e): Option<u64>
}

~struct File {
    ~open<P: AsRef<Path>>(path: P): Option<File>
    +get_u8(offset: u64, Endian: e): Option<u8>
    +get_u16(offset: u64, Endian: e): Option<u16>
    +get_u32(offset: u64, Endian: e): Option<u32>
    +get_u64(offset: u64, Endian: e): Option<u64>
}

ReadElf *-d- BinParser
BinParser <|.. Slice
BinParser <|.. VecBuffer
BinParser <|.. File
@enduml
